#LISTE AS FATURAS PARA AS QUAIS A REMESSA FOI PARA UMA CIDADE DIFERENTE DA CIDADE DO CLIENTE. CONSIDERE APENAS OS CLIENTES DO REINO UNIDO.
#A LISTAGEM DEVE INCLUIR :
-- O NR DA FATURA COMPLETANDO COM ZEROS PRINCIAPAIS 8 ITENS . POR EXEMPLO:00001234
-- A DATA DA FATURA NO FORMATO YYYY-MM-DD. POR EXEMPLO:1996-12-01
-- PARA A CIDADE DO CLIENTE
SELECT c.ClienteID,c.Cidade,c.Pais,fat.ClienteID, fat.CidadeEnvio,fat.DataFatura, concat('0000',fat.FaturaId)

from clientes as c
inner join faturas as fat
on c.ClienteID =fat.ClienteID
having  c.Pais = 'UK' and c.Cidade <>fat.CidadeEnvio 