-- MySQL Script generated by MySQL Workbench
-- Thu Sep 23 17:09:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NETFLIX
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NETFLIX
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NETFLIX` DEFAULT CHARACTER SET utf8mb4 ;
USE `NETFLIX` ;

-- -----------------------------------------------------
-- Table `NETFLIX`.`Atores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NETFLIX`.`Atores` (
  `idAtores` INT NOT NULL AUTO_INCREMENT,
  `nome_ator` VARCHAR(45) NULL,
  `sobrenome_Ator` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `pais_Origem` VARCHAR(10) NULL,
  PRIMARY KEY (`idAtores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NETFLIX`.`Generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NETFLIX`.`Generos` (
  `idGeneros` INT NOT NULL AUTO_INCREMENT,
  `nome_genero` VARCHAR(25) NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idGeneros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NETFLIX`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NETFLIX`.`Series` (
  `idSeries` INT NOT NULL AUTO_INCREMENT,
  `idGeneros` INT NOT NULL,
  `nome_Serie` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  `classisficação` INT NULL,
  PRIMARY KEY (`idSeries`),
  INDEX `idGenerosSeries_idx` (`idGeneros` ASC) VISIBLE,
  CONSTRAINT `idGenerosSeries`
    FOREIGN KEY (`idGeneros`)
    REFERENCES `NETFLIX`.`Generos` (`idGeneros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NETFLIX`.`Filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NETFLIX`.`Filmes` (
  `idFilmes` INT NOT NULL AUTO_INCREMENT,
  `idGenero` INT NOT NULL,
  `titulo_filme` VARCHAR(45) NULL,
  `ano_lancamento` DATE NULL,
  `classificacao` INT NULL,
  `sinopse` TEXT NULL,
  PRIMARY KEY (`idFilmes`),
  INDEX `idGeneroFilmes_idx` (`idGenero` ASC) VISIBLE,
  CONSTRAINT `idGeneroFilmes`
    FOREIGN KEY (`idGenero`)
    REFERENCES `NETFLIX`.`Generos` (`idGeneros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NETFLIX`.`Fatura_filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NETFLIX`.`Fatura_filmes` (
  `idFatura_filmes` INT NOT NULL AUTO_INCREMENT,
  `idFilmes` INT NOT NULL,
  `idAtor` INT NOT NULL,
  `Custo` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idFatura_filmes`),
  INDEX `idFilmesFatura_idx` (`idFilmes` ASC) VISIBLE,
  INDEX `idAtorFatura_idx` (`idAtor` ASC) VISIBLE,
  CONSTRAINT `idFilmesFatura`
    FOREIGN KEY (`idFilmes`)
    REFERENCES `NETFLIX`.`Filmes` (`idFilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAtorFatura`
    FOREIGN KEY (`idAtor`)
    REFERENCES `NETFLIX`.`Atores` (`idAtores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NETFLIX`.`Temporadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NETFLIX`.`Temporadas` (
  `idTemporada` INT NOT NULL AUTO_INCREMENT,
  `idSeries` INT NOT NULL,
  `descricao` TEXT NULL,
  `classisficação` INT NULL,
  `num_temporada` INT NULL,
  PRIMARY KEY (`idTemporada`),
  INDEX `idSeriesTemporada_idx` (`idSeries` ASC) VISIBLE,
  CONSTRAINT `idSeriesTemporada`
    FOREIGN KEY (`idSeries`)
    REFERENCES `NETFLIX`.`Series` (`idSeries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NETFLIX`.`Episodios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NETFLIX`.`Episodios` (
  `idEpisodios` INT NOT NULL AUTO_INCREMENT,
  `idTemporada` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sinopse_Episodio` TEXT(300) NULL,
  PRIMARY KEY (`idEpisodios`),
  INDEX `idTemporada_idx` (`idTemporada` ASC) VISIBLE,
  CONSTRAINT `idTemporada`
    FOREIGN KEY (`idTemporada`)
    REFERENCES `NETFLIX`.`Temporadas` (`idTemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NETFLIX`.`Fatura_Episodio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NETFLIX`.`Fatura_Episodio` (
  `idFatura_Episodio` INT NOT NULL AUTO_INCREMENT,
  `idEpisodio` INT NOT NULL,
  `idAtor` INT NOT NULL,
  `Custo` DECIMAL(10,2) NULL,
  `qde_Episodio` INT NULL,
  PRIMARY KEY (`idFatura_Episodio`),
  INDEX `idEpisodioFaturaEp_idx` (`idEpisodio` ASC) VISIBLE,
  INDEX `idAtorfatura_idx` (`idAtor` ASC) VISIBLE,
  CONSTRAINT `idEpisodioFaturaEp`
    FOREIGN KEY (`idEpisodio`)
    REFERENCES `NETFLIX`.`Episodios` (`idEpisodios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAtorfatura`
    FOREIGN KEY (`idAtor`)
    REFERENCES `NETFLIX`.`Atores` (`idAtores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
