-- MySQL Script generated by MySQL Workbench
-- Tue Sep  7 19:21:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CARREFOUR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CARREFOUR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CARREFOUR` DEFAULT CHARACTER SET utf8mb4 ;
USE `CARREFOUR` ;

-- -----------------------------------------------------
-- Table `CARREFOUR`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARREFOUR`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome_Fornecedor` VARCHAR(45) NULL,
  `cnpj` CHAR(16) NULL,
  `nome_respons` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARREFOUR`.`Fone_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARREFOUR`.`Fone_Fornecedor` (
  `idFone_Fornecedor` INT NOT NULL AUTO_INCREMENT,
  `ddd` INT NOT NULL,
  `celular` INT NOT NULL,
  `fixo` INT NULL,
  `idFornecedor` INT NOT NULL,
  PRIMARY KEY (`idFone_Fornecedor`),
  UNIQUE INDEX `idFone_Fornecedor_UNIQUE` (`idFone_Fornecedor` ASC) VISIBLE,
  INDEX `idFornecedorFone_idx` (`idFornecedor` ASC) VISIBLE,
  CONSTRAINT `idFornecedorFone`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `CARREFOUR`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARREFOUR`.`Endereco_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARREFOUR`.`Endereco_Fornecedor` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `idFornecedor` INT NULL,
  `nome_Fornecedor` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `cep` CHAR(9) NULL,
  `bairro` VARCHAR(15) NULL,
  `estado` VARCHAR(15) NULL,
  `cidade` VARCHAR(15) NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `idFornecedorEndereco_idx` (`idFornecedor` ASC) VISIBLE,
  CONSTRAINT `idFornecedorEndereco`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `CARREFOUR`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARREFOUR`.`Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARREFOUR`.`Sessao` (
  `idSessao` INT NOT NULL AUTO_INCREMENT,
  `nome_Sessao` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  `Tipo_Produto` VARCHAR(15) NULL,
  PRIMARY KEY (`idSessao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARREFOUR`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARREFOUR`.`Produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `idFornecedor` INT NULL,
  `nome_Produto` VARCHAR(45) NULL,
  `idSessao` INT NULL,
  `nume_lote` CHAR(15) NULL,
  `data_compra` DATE NULL,
  `valor_unit` DECIMAL(6,2) NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idProdutos`),
  INDEX `idFornecedorProduto_idx` (`idFornecedor` ASC) VISIBLE,
  INDEX `idSessaoProdutos_idx` (`idSessao` ASC) VISIBLE,
  CONSTRAINT `idFornecedorProduto`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `CARREFOUR`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSessaoProdutos`
    FOREIGN KEY (`idSessao`)
    REFERENCES `CARREFOUR`.`Sessao` (`idSessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARREFOUR`.`VALIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARREFOUR`.`VALIDADES` (
  `idValidade` INT NOT NULL AUTO_INCREMENT,
  `idProdutos` INT NULL,
  `data_validade` DATE NULL,
  `vencido` TINYINT(2) NULL,
  PRIMARY KEY (`idValidade`),
  CONSTRAINT `idProdutosValidade`
    FOREIGN KEY (`idProdutos`)
    REFERENCES `CARREFOUR`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
