-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 13:46:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EMPRESA-SEGURADORA
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema b'seguradora'
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SEGURADORA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SEGURADORA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SEGURADORA` ;
USE `SEGURADORA` ;

-- -----------------------------------------------------
-- Table `SEGURADORA`.`EMPRESASEGURADORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SEGURADORA`.`EMPRESASEGURADORA` (
  `id_empresa` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(20) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `nome_fantasia` VARCHAR(20) NOT NULL,
  `fone_empresa` CHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(14) NOT NULL,
  `logradouro` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` CHAR(10) NULL DEFAULT NULL,
  `cidade` CHAR(10) NULL DEFAULT NULL,
  `estado` CHAR(8) NULL DEFAULT NULL,
  `cep` CHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX (`nome_fantasia` ASC) VISIBLE,
  UNIQUE INDEX (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `SEGURADORA`.`PROPRIETARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SEGURADORA`.`PROPRIETARIOS` (
  `id_proprietario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(20) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `nome_fantasia` VARCHAR(20) NULL DEFAULT NULL,
  `fone_empresa` CHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(14) NULL DEFAULT NULL,
  `logradouro` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` CHAR(10) NULL DEFAULT NULL,
  `cidade` CHAR(10) NULL DEFAULT NULL,
  `estado` CHAR(8) NULL DEFAULT NULL,
  `cep` CHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proprietario`),
  UNIQUE INDEX (`cnpj` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `SEGURADORA`.`EMPRESASEGURADORA` ());


-- -----------------------------------------------------
-- Table `SEGURADORA`.`AGENTE_SEGUROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SEGURADORA`.`AGENTE_SEGUROS` (
  `id_agente` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_agente` VARCHAR(20) NOT NULL,
  `num_doc` VARCHAR(14) NOT NULL,
  `fone_agente` CHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(14) NULL DEFAULT NULL,
  `logradouro` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` CHAR(10) NULL DEFAULT NULL,
  `cidade` CHAR(10) NULL DEFAULT NULL,
  `estado` CHAR(8) NULL DEFAULT NULL,
  `cep` CHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id_agente`),
  UNIQUE INDEX (`num_doc` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `SEGURADORA`.`TIPODOC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SEGURADORA`.`TIPODOC` (
  `id_tipodoc` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `tipodoc` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id_tipodoc`),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `SEGURADORA`.`PROPRIETARIOS` (),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `SEGURADORA`.`AGENTE_SEGUROS` ());


-- -----------------------------------------------------
-- Table `SEGURADORA`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SEGURADORA`.`VEICULO` (
  `id_veiculo` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `marca` VARCHAR(10) NOT NULL,
  `modelo` VARCHAR(8) NOT NULL,
  `placa` VARCHAR(7) NULL DEFAULT NULL,
  `CHASSIS` VARCHAR(14) NULL DEFAULT NULL,
  `portas` TINYINT(2) NULL DEFAULT NULL,
  `patente` CHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id_veiculo`),
  UNIQUE INDEX (`modelo` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `SEGURADORA`.`PROPRIETARIOS` (),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `SEGURADORA`.`TIPOVEICULOS` ());


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
